### ISSUE TITLE
Meet with Ag Department heads

### ISSUE THREAD

**Issue by olendorf** [olendorf/data_crm#2]
Meeting set up for March 14, 8:00-9:30

Contact: Erikia Stover - ess9@psu.edu

**Comment by olendorf** [comment]
I met with them today. They seemed fairly receptive. It was an 8am meeting right after spring break and the time change though. Several people asked for the slides. There were also a number of good questions which is always good. 

I will close the thread once I have finished with followup emails.

**Comment by patriciahswe** [comment]
@olendorf Sounds promising, despite the early hour and unfortunately timing of the time change! I'm looking forward to catching up later this week about data stuff.

**Comment by olendorf** [comment]
Closing this one. Finished with response emails and such.
